# Generated by Django 2.2.3 on 2020-08-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default='blog content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.TextField(default='blog title'),
        ),
    ]
