# Generated by Django 2.2.3 on 2020-08-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200805_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.TextField(blank=True, default='blog title', null=True),
        ),
    ]
