# Generated by Django 2.2.3 on 2020-08-10 13:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200805_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='richcontent',
            field=ckeditor.fields.RichTextField(default='None'),
        ),
    ]
