# Generated by Django 2.2.3 on 2020-08-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blogpost_richcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='contents',
        ),
    ]
