# Generated by Django 2.2.3 on 2020-08-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200810_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='richcontent',
        ),
    ]
