# Generated by Django 2.2.3 on 2020-08-11 19:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_blogpost_richcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='richcontent',
            field=ckeditor.fields.RichTextField(default='None'),
        ),
    ]
